# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/node:10.16.3
#     steps:
#       - checkout
#       - run: npm install
#       - run: npm run test

version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install eslint
      - run: npm run lint
  node-6.0:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run test

  node-14:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run test

  codecov:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run test-coverage
      - run: npm run codecov

workflows:
  version: 2
  build:
    jobs:
      - lint
      - node-6.0
      - node-14
      - codecov
